crypto_data = [
    {"Rank": 1, "Ticker": YTicker("JTO"), "Name": "Jito", "Market Cap": 490_000_000},
    {"Rank": 2, "Ticker": YTicker("ZEC"), "Name": "Zcash", "Market Cap": 485_000_000},
    {"Rank": 3, "Ticker": YTicker("RUNE-USD"), "Name": "THORChain", "Market Cap": 480_000_000},
    {"Rank": 4, "Ticker": YTicker("1INCH-USD"), "Name": "1inch Network", "Market Cap": 475_000_000},
    {"Rank": 5, "Ticker": YTicker("MANA-USD"), "Name": "Decentraland", "Market Cap": 470_000_000},
    {"Rank": 6, "Ticker": YTicker("SAND-USD"), "Name": "The Sandbox", "Market Cap": 465_000_000},
    {"Rank": 7, "Ticker": YTicker("CHZ-USD"), "Name": "Chiliz", "Market Cap": 460_000_000},
    {"Rank": 8, "Ticker": YTicker("AXS-USD"), "Name": "Axie Infinity", "Market Cap": 455_000_000},
    {"Rank": 9, "Ticker": YTicker("GALA-USD"), "Name": "Gala", "Market Cap": 450_000_000},
    {"Rank": 10, "Ticker": YTicker("LRC-USD"), "Name": "Loopring", "Market Cap": 445_000_000},
    {"Rank": 11, "Ticker": YTicker("CRV-USD"), "Name": "Curve DAO Token", "Market Cap": 440_000_000},
    {"Rank": 12, "Ticker": YTicker("COMP-USD"), "Name": "Compound", "Market Cap": 435_000_000},
    {"Rank": 13, "Ticker": YTicker("MKR-USD"), "Name": "Maker", "Market Cap": 430_000_000},
    {"Rank": 14, "Ticker": YTicker("AAVE-USD"), "Name": "Aave", "Market Cap": 425_000_000},
    {"Rank": 15, "Ticker": YTicker("SNX-USD"), "Name": "Synthetix", "Market Cap": 420_000_000},
    {"Rank": 16, "Ticker": YTicker("YFI-USD"), "Name": "yearn.finance", "Market Cap": 415_000_000},
    {"Rank": 17, "Ticker": YTicker("BAL-USD"), "Name": "Balancer", "Market Cap": 410_000_000},
    {"Rank": 18, "Ticker": YTicker("REN-USD"), "Name": "Ren", "Market Cap": 405_000_000},
    {"Rank": 19, "Ticker": YTicker("ZRX-USD"), "Name": "0x", "Market Cap": 400_000_000},
    {"Rank": 20, "Ticker": YTicker("KNC-USD"), "Name": "Kyber Network", "Market Cap": 395_000_000},
    {"Rank": 21, "Ticker": YTicker("BAND-USD"), "Name": "Band Protocol", "Market Cap": 390_000_000},
    {"Rank": 22, "Ticker": YTicker("RSR-USD"), "Name": "Reserve Rights", "Market Cap": 385_000_000},
    {"Rank": 23, "Ticker": YTicker("OCEAN-USD"), "Name": "Ocean Protocol", "Market Cap": 380_000_000},
    {"Rank": 24, "Ticker": YTicker("FET-USD"), "Name": "Fetch.ai", "Market Cap": 375_000_000},
    {"Rank": 25, "Ticker": YTicker("RNDR-USD"), "Name": "Render Token", "Market Cap": 370_000_000},
    {"Rank": 26, "Ticker": YTicker("GRT-USD"), "Name": "The Graph", "Market Cap": 365_000_000},
    {"Rank": 27, "Ticker": YTicker("BAT-USD"), "Name": "Basic Attention Token", "Market Cap": 360_000_000},
    {"Rank": 28, "Ticker": YTicker("ENJ-USD"), "Name": "Enjin Coin", "Market Cap": 355_000_000},
    {"rank": 21, "ticker": "BAND", "yTicker": "BAND-USD", "name": "Band Protocol", "market_cap_usd": 390_000_000},
    {"rank": 22, "ticker": "RSR", "yTicker": "RSR-USD", "name": "Reserve Rights", "market_cap_usd": 385_000_000},
    {"rank": 23, "ticker": "OCEAN", "yTicker": "OCEAN-USD", "name": "Ocean Protocol", "market_cap_usd": 380_000_000},
    {"rank": 24, "ticker": "FET", "yTicker": "FET-USD", "name": "Fetch.ai", "market_cap_usd": 375_000_000},
    {"rank": 25, "ticker": "RNDR", "yTicker": "RNDR-USD", "name": "Render Token", "market_cap_usd": 370_000_000},
    {"rank": 26, "ticker": "GRT", "yTicker": "GRT-USD", "name": "The Graph", "market_cap_usd": 365_000_000},
    {"rank": 27, "ticker": "BAT", "yTicker": "BAT-USD", "name": "Basic Attention Token", "market_cap_usd": 360_000_000},
    {"rank": 28, "ticker": "ENJ", "yTicker": "ENJ-USD", "name": "Enjin Coin", "market_cap_usd": 355_000_000},
    {"rank": 29, "ticker": "MANA", "yTicker": "MANA-USD", "name": "Decentraland", "market_cap_usd": 350_000_000},
    {"rank": 30, "ticker": "DYDX", "yTicker": "DYDX-USD", "name": "dYdX", "market_cap_usd": 345_000_000},
    {"rank": 31, "ticker": "IMX", "yTicker": "IMX-USD", "name": "Immutable X", "market_cap_usd": 340_000_000},
    {"rank": 32, "ticker": "LPT", "yTicker": "LPT-USD", "name": "Livepeer", "market_cap_usd": 335_000_000},
    {"rank": 33, "ticker": "MASK", "yTicker": "MASK-USD", "name": "Mask Network", "market_cap_usd": 330_000_000},
    {"rank": 34, "ticker": "API3", "yTicker": "API3-USD", "name": "API3", "market_cap_usd": 325_000_000},
    {"rank": 35, "ticker": "ACH", "yTicker": "ACH-USD", "name": "Alchemy Pay", "market_cap_usd": 320_000_000},
    {"rank": 36, "ticker": "ANKR", "yTicker": "ANKR-USD", "name": "Ankr", "market_cap_usd": 315_000_000},
    {"rank": 37, "ticker": "NMR", "yTicker": "NMR-USD", "name": "Numeraire", "market_cap_usd": 310_000_000},
    {"rank": 38, "ticker": "UMA", "yTicker": "UMA-USD", "name": "UMA", "market_cap_usd": 305_000_000},
    {"rank": 39, "ticker": "BADGER", "yTicker": "BADGER-USD", "name": "Badger DAO", "market_cap_usd": 300_000_000},
    {"rank": 40, "ticker": "RARI", "yTicker": "RARI-USD", "name": "Rarible", "market_cap_usd": 295_000_000},
    {"rank": 41, "ticker": "MLN", "yTicker": "MLN-USD", "name": "Melon", "market_cap_usd": 290_000_000},
    {"rank": 42, "ticker": "BNT", "yTicker": "BNT-USD", "name": "Bancor", "market_cap_usd": 285_000_000},
    {"rank": 43, "ticker": "KP3R", "yTicker": "KP3R-USD", "name": "Keep3rV1", "market_cap_usd": 280_000_000},
    {"rank": 44, "ticker": "PERP", "yTicker": "PERP-USD", "name": "Perpetual Protocol", "market_cap_usd": 275_000_000},
    {"rank": 45, "ticker": "ALPHA", "yTicker": "ALPHA-USD", "name": "Alpha Finance Lab", "market_cap_usd": 270_000_000},
    {"rank": 46, "ticker": "CREAM", "yTicker": "CREAM-USD", "name": "Cream Finance", "market_cap_usd": 265_000_000},
    {"rank": 47, "ticker": "SRM", "yTicker": "SRM-USD", "name": "Serum", "market_cap_usd": 260_000_000},
    {"rank": 48, "ticker": "RAY", "yTicker": "RAY-USD", "name": "Raydium", "market_cap_usd": 255_000_000},
    {"rank": 49, "ticker": "COPE", "yTicker": "COPE-USD", "name": "Cope", "market_cap_usd": 250_000_000},
    {"rank": 50, "ticker": "FIDA", "yTicker": "FIDA-USD", "name": "Bonfida", "market_cap_usd": 245_000_000},
    {"rank": 21, "ticker": "BAND", "yTicker": "BAND-USD", "name": "Band Protocol", "market_cap_usd": 390_000_000},
    {"rank": 22, "ticker": "RSR", "yTicker": "RSR-USD", "name": "Reserve Rights", "market_cap_usd": 385_000_000},
    {"rank": 23, "ticker": "OCEAN", "yTicker": "OCEAN-USD", "name": "Ocean Protocol", "market_cap_usd": 380_000_000},
    {"rank": 24, "ticker": "FET", "yTicker": "FET-USD", "name": "Fetch.ai", "market_cap_usd": 375_000_000},
    {"rank": 25, "ticker": "RNDR", "yTicker": "RNDR-USD", "name": "Render Token", "market_cap_usd": 370_000_000},
    {"rank": 26, "ticker": "GRT", "yTicker": "GRT-USD", "name": "The Graph", "market_cap_usd": 365_000_000},
    {"rank": 27, "ticker": "BAT", "yTicker": "BAT-USD", "name": "Basic Attention Token", "market_cap_usd": 360_000_000},
    {"rank": 28, "ticker": "ENJ", "yTicker": "ENJ-USD", "name": "Enjin Coin", "market_cap_usd": 355_000_000},
    {"rank": 29, "ticker": "MANA", "yTicker": "MANA-USD", "name": "Decentraland", "market_cap_usd": 350_000_000},
    {"rank": 30, "ticker": "DYDX", "yTicker": "DYDX-USD", "name": "dYdX", "market_cap_usd": 345_000_000},
    {"rank": 31, "ticker": "IMX", "yTicker": "IMX-USD", "name": "Immutable X", "market_cap_usd": 340_000_000},
    {"rank": 32, "ticker": "LPT", "yTicker": "LPT-USD", "name": "Livepeer", "market_cap_usd": 335_000_000},
    {"rank": 33, "ticker": "MASK", "yTicker": "MASK-USD", "name": "Mask Network", "market_cap_usd": 330_000_000},
    {"rank": 34, "ticker": "API3", "yTicker": "API3-USD", "name": "API3", "market_cap_usd": 325_000_000},
    {"rank": 35, "ticker": "ACH", "yTicker": "ACH-USD", "name": "Alchemy Pay", "market_cap_usd": 320_000_000},
    {"rank": 36, "ticker": "ANKR", "yTicker": "ANKR-USD", "name": "Ankr", "market_cap_usd": 315_000_000},
    {"rank": 37, "ticker": "NMR", "yTicker": "NMR-USD", "name": "Numeraire", "market_cap_usd": 310_000_000},
    {"rank": 38, "ticker": "UMA", "yTicker": "UMA-USD", "name": "UMA", "market_cap_usd": 305_000_000},
    {"rank": 39, "ticker": "BADGER", "yTicker": "BADGER-USD", "name": "Badger DAO", "market_cap_usd": 300_000_000},
    {"rank": 40, "ticker": "RARI", "yTicker": "RARI-USD", "name": "Rarible", "market_cap_usd": 295_000_000},
    {"rank": 41, "ticker": "MLN", "yTicker": "MLN-USD", "name": "Melon", "market_cap_usd": 290_000_000},
    {"rank": 42, "ticker": "BNT", "yTicker": "BNT-USD", "name": "Bancor", "market_cap_usd": 285_000_000},
    {"rank": 43, "ticker": "KP3R", "yTicker": "KP3R-USD", "name": "Keep3rV1", "market_cap_usd": 280_000_000},
    {"rank": 44, "ticker": "PERP", "yTicker": "PERP-USD", "name": "Perpetual Protocol", "market_cap_usd": 275_000_000},
    {"rank": 45, "ticker": "ALPHA", "yTicker": "ALPHA-USD", "name": "Alpha Finance Lab", "market_cap_usd": 270_000_000},
    {"rank": 46, "ticker": "CREAM", "yTicker": "CREAM-USD", "name": "Cream Finance", "market_cap_usd": 265_000_000},
    {"rank": 47, "ticker": "SRM", "yTicker": "SRM-USD", "name": "Serum", "market_cap_usd": 260_000_000},
    {"rank": 48, "ticker": "RAY", "yTicker": "RAY-USD", "name": "Raydium", "market_cap_usd": 255_000_000},
    {"rank": 49, "ticker": "COPE", "yTicker": "COPE-USD", "name": "Cope", "market_cap_usd": 250_000_000},
    {"rank": 50, "ticker": "FIDA", "yTicker": "FIDA-USD", "name": "Bonfida", "market_cap_usd": 245_000_000},
    {"Rank": 71, "Ticker": "BFC", "yTicker": "BFC-USD", "Name": "Bifrost", "MarketCapUSD": 140_000_000},
    {"Rank": 72, "Ticker": "REEF", "yTicker": "REEF-USD", "Name": "Reef Finance", "MarketCapUSD": 135_000_000},
    {"Rank": 73, "Ticker": "TLM", "yTicker": "TLM-USD", "Name": "Alien Worlds", "MarketCapUSD": 130_000_000},
    {"Rank": 74, "Ticker": "WIN", "yTicker": "WIN-USD", "Name": "WINkLink", "MarketCapUSD": 125_000_000},
    {"Rank": 75, "Ticker": "SUN", "yTicker": "SUN-USD", "Name": "Sun Token", "MarketCapUSD": 120_000_000},
    {"Rank": 76, "Ticker": "JST", "yTicker": "JST-USD", "Name": "JUST", "MarketCapUSD": 115_000_000},
    {"Rank": 77, "Ticker": "BTT", "yTicker": "BTT-USD", "Name": "BitTorrent", "MarketCapUSD": 110_000_000},
    {"Rank": 78, "Ticker": "NFT", "yTicker": "NFT-USD", "Name": "APENFT", "MarketCapUSD": 105_000_000},
    {"Rank": 79, "Ticker": "WINK", "yTicker": "WINK-USD", "Name": "WINk", "MarketCapUSD": 100_000_000},
    {"Rank": 80, "Ticker": "DGB", "yTicker": "DGB-USD", "Name": "DigiByte", "MarketCapUSD": 95_000_000},
    {"Rank": 81, "Ticker": "SC", "yTicker": "SC-USD", "Name": "Siacoin", "MarketCapUSD": 90_000_000},
    {"Rank": 82, "Ticker": "ZEN", "yTicker": "ZEN-USD", "Name": "Horizen", "MarketCapUSD": 85_000_000},
    {"Rank": 83, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 80_000_000},
    {"Rank": 84, "Ticker": "STORJ", "yTicker": "STORJ-USD", "Name": "Storj", "MarketCapUSD": 75_000_000},
    {"Rank": 85, "Ticker": "ARDR", "yTicker": "ARDR-USD", "Name": "Ardor", "MarketCapUSD": 70_000_000},
    {"Rank": 86, "Ticker": "WAVES", "yTicker": "WAVES-USD", "Name": "Waves", "MarketCapUSD": 65_000_000},
    {"Rank": 87, "Ticker": "LSK", "yTicker": "LSK-USD", "Name": "Lisk", "MarketCapUSD": 60_000_000},
    {"Rank": 88, "Ticker": "STRAT", "yTicker": "STRAT-USD", "Name": "Stratis", "MarketCapUSD": 55_000_000},
    {"Rank": 89, "Ticker": "ARK", "yTicker": "ARK-USD", "Name": "Ark", "MarketCapUSD": 50_000_000},
    {"Rank": 90, "Ticker": "KMD", "yTicker": "KMD-USD", "Name": "Komodo", "MarketCapUSD": 45_000_000},
    {"Rank": 91, "Ticker": "PIVX", "yTicker": "PIVX-USD", "Name": "PIVX", "MarketCapUSD": 40_000_000},
    {"Rank": 92, "Ticker": "NAV", "yTicker": "NAV-USD", "Name": "NavCoin", "MarketCapUSD": 35_000_000},
    {"Rank": 93, "Ticker": "VTC", "yTicker": "VTC-USD", "Name": "Vertcoin", "MarketCapUSD": 30_000_000},
    {"Rank": 94, "Ticker": "MONA", "yTicker": "MONA-USD", "Name": "MonaCoin", "MarketCapUSD": 25_000_000},
    {"Rank": 95, "Ticker": "XCP", "yTicker": "XCP-USD", "Name": "Counterparty", "MarketCapUSD": 20_000_000},
    {"Rank": 96, "Ticker": "BURST", "yTicker": "BURST-USD", "Name": "Burst", "MarketCapUSD": 18_000_000},
    {"Rank": 97, "Ticker": "NXT", "yTicker": "NXT-USD", "Name": "Nxt", "MarketCapUSD": 16_000_000},
    {"Rank": 98, "Ticker": "CLOAK", "yTicker": "CLOAK-USD", "Name": "CloakCoin", "MarketCapUSD": 14_000_000},
    {"Rank": 99, "Ticker": "POT", "yTicker": "POT-USD", "Name": "PotCoin", "MarketCapUSD": 12_000_000},
    {"Rank": 100, "Ticker": "PINK", "yTicker": "PINK-USD", "Name": "PinkCoin", "MarketCapUSD": 10_000_000},
    {"Rank": 101, "Ticker": "AC", "yTicker": "AC-USD", "Name": "AsiaCoin", "MarketCapUSD": 9_500_000},
    {"Rank": 102, "Ticker": "COVAL", "yTicker": "COVAL-USD", "Name": "Circuits of Value", "MarketCapUSD": 9_000_000},
    {"Rank": 103, "Ticker": "NXS", "yTicker": "NXS-USD", "Name": "Nexus", "MarketCapUSD": 8_500_000},
    {"Rank": 104, "Ticker": "QRL", "yTicker": "QRL-USD", "Name": "Quantum Resistant Ledger", "MarketCapUSD": 8_000_000},
    {"Rank": 105, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 7_500_000},
    {"Rank": 106, "Ticker": "WTC", "yTicker": "WTC-USD", "Name": "Waltonchain", "MarketCapUSD": 7_000_000},
    {"Rank": 107, "Ticker": "BTM", "yTicker": "BTM-USD", "Name": "Bytom", "MarketCapUSD": 6_500_000},
    {"Rank": 108, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 6_000_000},
    {"Rank": 109, "Ticker": "ENG", "yTicker": "ENG-USD", "Name": "Enigma", "MarketCapUSD": 5_500_000},
    {"Rank": 110, "Ticker": "FCT", "yTicker": "FCT-USD", "Name": "Factom", "MarketCapUSD": 5_000_000},
    {"Rank": 111, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 4_800_000},
    {"Rank": 112, "Ticker": "ELF", "yTicker": "ELF-USD", "Name": "aelf", "MarketCapUSD": 4_600_000},
    {"Rank": 113, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 4_400_000},
    {"Rank": 114, "Ticker": "VIA", "yTicker": "VIA-USD", "Name": "Viacoin", "MarketCapUSD": 4_200_000},
    {"Rank": 115, "Ticker": "MCO", "yTicker": "MCO-USD", "Name": "Crypto.com Coin", "MarketCapUSD": 4_000_000},
    {"Rank": 116, "Ticker": "NAV", "yTicker": "NAV-USD", "Name": "NavCoin", "MarketCapUSD": 3_800_000},
    {"Rank": 117, "Ticker": "XEM", "yTicker": "XEM-USD", "Name": "NEM", "MarketCapUSD": 3_600_000},
    {"Rank": 118, "Ticker": "PPT", "yTicker": "PPT-USD", "Name": "Populous", "MarketCapUSD": 3_400_000},
    {"Rank": 119, "Ticker": "QKC", "yTicker": "QKC-USD", "Name": "QuarkChain", "MarketCapUSD": 3_200_000},
    {"Rank": 120, "Ticker": "DGB", "yTicker": "DGB-USD", "Name": "DigiByte", "MarketCapUSD": 3_000_000},
    {"Rank": 121, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 2_800_000},
    {"Rank": 122, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 2_600_000},
    {"Rank": 123, "Ticker": "CND", "yTicker": "CND-USD", "Name": "Cindicator", "MarketCapUSD": 2_400_000},
    {"Rank": 124, "Ticker": "POWR", "yTicker": "POWR-USD", "Name": "Power Ledger", "MarketCapUSD": 2_200_000},
    {"Rank": 125, "Ticker": "PIVX", "yTicker": "PIVX-USD", "Name": "PIVX", "MarketCapUSD": 2_000_000},
    {"Rank": 126, "Ticker": "MAID", "yTicker": "MAID-USD", "Name": "MaidSafeCoin", "MarketCapUSD": 1_800_000},
    {"Rank": 127, "Ticker": "REP", "yTicker": "REP-USD", "Name": "Augur", "MarketCapUSD": 1_600_000},
    {"Rank": 128, "Ticker": "BTS", "yTicker": "BTS-USD", "Name": "BitShares", "MarketCapUSD": 1_400_000},
    {"Rank": 129, "Ticker": "CVC", "yTicker": "CVC-USD", "Name": "Civic", "MarketCapUSD": 1_200_000},
    {"Rank": 130, "Ticker": "STORM", "yTicker": "STORM-USD", "Name": "StormX", "MarketCapUSD": 1_000_000},
    {"Rank": 131, "Ticker": "NANO", "yTicker": "NANO-USD", "Name": "Nano", "MarketCapUSD": 950_000},
    {"Rank": 132, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 900_000},
    {"Rank": 133, "Ticker": "GNT", "yTicker": "GNT-USD", "Name": "Golem", "MarketCapUSD": 850_000},
    {"Rank": 134, "Ticker": "POE", "yTicker": "POE-USD", "Name": "Po.et", "MarketCapUSD": 800_000},
    {"Rank": 135, "Ticker": "MOD", "yTicker": "MOD-USD", "Name": "Modum", "MarketCapUSD": 750_000},
    {"Rank": 136, "Ticker": "GXS", "yTicker": "GXS-USD", "Name": "GXShares", "MarketCapUSD": 700_000},
    {"Rank": 137, "Ticker": "ZEN", "yTicker": "ZEN-USD", "Name": "Horizen", "MarketCapUSD": 650_000},
    {"Rank": 138, "Ticker": "CMT", "yTicker": "CMT-USD", "Name": "CyberMiles", "MarketCapUSD": 600_000},
    {"Rank": 139, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 550_000},
    {"Rank": 140, "Ticker": "MANA", "yTicker": "MANA-USD", "Name": "Decentraland", "MarketCapUSD": 500_000},
    {"Rank": 141, "Ticker": "KNC", "yTicker": "KNC-USD", "Name": "Kyber Network", "MarketCapUSD": 450_000},
    {"Rank": 142, "Ticker": "CND", "yTicker": "CND-USD", "Name": "Cindicator", "MarketCapUSD": 400_000},
    {"Rank": 143, "Ticker": "ENJ", "yTicker": "ENJ-USD", "Name": "Enjin Coin", "MarketCapUSD": 350_000},
    {"Rank": 144, "Ticker": "REQ", "yTicker": "REQ-USD", "Name": "Request", "MarketCapUSD": 300_000},
    {"Rank": 145, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 250_000},
    {"Rank": 146, "Ticker": "AST", "yTicker": "AST-USD", "Name": "AirSwap", "MarketCapUSD": 200_000},
    {"Rank": 147, "Ticker": "LEND", "yTicker": "LEND-USD", "Name": "Aave (old LEND)", "MarketCapUSD": 150_000},
    {"Rank": 148, "Ticker": "TRIG", "yTicker": "TRIG-USD", "Name": "Trigger", "MarketCapUSD": 100_000},
    {"Rank": 149, "Ticker": "NMR", "yTicker": "NMR-USD", "Name": "Numeraire", "MarketCapUSD": 75_000},
    {"Rank": 150, "Ticker": "POA", "yTicker": "POA-USD", "Name": "POA Network", "MarketCapUSD": 50_000},
    {"Rank": 151, "Ticker": "KIN", "yTicker": "KIN-USD", "Name": "Kin", "MarketCapUSD": 48_000},
    {"Rank": 152, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 46_000},
    {"Rank": 153, "Ticker": "STX", "yTicker": "STX-USD", "Name": "Stacks", "MarketCapUSD": 44_000},
    {"Rank": 154, "Ticker": "CVC", "yTicker": "CVC-USD", "Name": "Civic", "MarketCapUSD": 42_000},
    {"Rank": 155, "Ticker": "WAXP", "yTicker": "WAXP-USD", "Name": "WAX", "MarketCapUSD": 40_000},
    {"Rank": 156, "Ticker": "HIVE", "yTicker": "HIVE-USD", "Name": "Hive", "MarketCapUSD": 38_000},
    {"Rank": 157, "Ticker": "STORJ", "yTicker": "STORJ-USD", "Name": "Storj", "MarketCapUSD": 36_000},
    {"Rank": 158, "Ticker": "CND", "yTicker": "CND-USD", "Name": "Cindicator", "MarketCapUSD": 34_000},
    {"Rank": 159, "Ticker": "WINGS", "yTicker": "WINGS-USD", "Name": "Wings DAO", "MarketCapUSD": 32_000},
    {"Rank": 160, "Ticker": "BNT", "yTicker": "BNT-USD", "Name": "Bancor", "MarketCapUSD": 30_000},
    {"Rank": 161, "Ticker": "ANT", "yTicker": "ANT-USD", "Name": "Aragon", "MarketCapUSD": 28_000},
    {"Rank": 162, "Ticker": "MTL", "yTicker": "MTL-USD", "Name": "Metal", "MarketCapUSD": 26_000},
    {"Rank": 163, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 24_000},
    {"Rank": 164, "Ticker": "MDS", "yTicker": "MDS-USD", "Name": "MediShares", "MarketCapUSD": 22_000},
    {"Rank": 165, "Ticker": "NXT", "yTicker": "NXT-USD", "Name": "Nxt", "MarketCapUSD": 20_000},
    {"Rank": 166, "Ticker": "BLOCK", "yTicker": "BLOCK-USD", "Name": "Blocknet", "MarketCapUSD": 18_000},
    {"Rank": 167, "Ticker": "PRL", "yTicker": "PRL-USD", "Name": "Oyster Pearl", "MarketCapUSD": 16_000},
    {"Rank": 168, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 14_000},
    {"Rank": 169, "Ticker": "ADX", "yTicker": "ADX-USD", "Name": "AdEx", "MarketCapUSD": 12_000},
    {"Rank": 170, "Ticker": "NMR", "yTicker": "NMR-USD", "Name": "Numeraire", "MarketCapUSD": 10_000},
    {"Rank": 171, "Ticker": "DGD", "yTicker": "DGD-USD", "Name": "DigixDAO", "MarketCapUSD": 9_500},
    {"Rank": 172, "Ticker": "REP", "yTicker": "REP-USD", "Name": "Augur", "MarketCapUSD": 9_000},
    {"Rank": 173, "Ticker": "RDN", "yTicker": "RDN-USD", "Name": "Raiden Network", "MarketCapUSD": 8_500},
    {"Rank": 174, "Ticker": "EDG", "yTicker": "EDG-USD", "Name": "Edgeless", "MarketCapUSD": 8_000},
    {"Rank": 175, "Ticker": "QSP", "yTicker": "QSP-USD", "Name": "Quantstamp", "MarketCapUSD": 7_500},
    {"Rank": 176, "Ticker": "MANA", "yTicker": "MANA-USD", "Name": "Decentraland", "MarketCapUSD": 7_000},
    {"Rank": 177, "Ticker": "POLY", "yTicker": "POLY-USD", "Name": "Polymath", "MarketCapUSD": 6_500},
    {"Rank": 178, "Ticker": "RFR", "yTicker": "RFR-USD", "Name": "Refereum", "MarketCapUSD": 6_000},
    {"Rank": 179, "Ticker": "C20", "yTicker": "C20-USD", "Name": "Crypto20", "MarketCapUSD": 5_500},
    {"Rank": 180, "Ticker": "TRST", "yTicker": "TRST-USD", "Name": "WeTrust", "MarketCapUSD": 5_000},
    {"Rank": 181, "Ticker": "WTC", "yTicker": "WTC-USD", "Name": "Waltonchain", "MarketCapUSD": 4_800},
    {"Rank": 182, "Ticker": "PAY", "yTicker": "PAY-USD", "Name": "TenX", "MarketCapUSD": 4_600},
    {"Rank": 183, "Ticker": "KMD", "yTicker": "KMD-USD", "Name": "Komodo", "MarketCapUSD": 4_400},
    {"Rank": 184, "Ticker": "PPT", "yTicker": "PPT-USD", "Name": "Populous", "MarketCapUSD": 4_200},
    {"Rank": 185, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 4_000},
    {"Rank": 186, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 3_800},
    {"Rank": 187, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 3_600},
    {"Rank": 188, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 3_400},
    {"Rank": 189, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 3_200},
    {"Rank": 190, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 3_000},
    {"Rank": 191, "Ticker": "CMT", "yTicker": "CMT-USD", "Name": "CyberMiles", "MarketCapUSD": 2_800},
    {"Rank": 192, "Ticker": "STMX", "yTicker": "STMX-USD", "Name": "StormX", "MarketCapUSD": 2_600},
    {"Rank": 193, "Ticker": "ADX", "yTicker": "ADX-USD", "Name": "AdEx", "MarketCapUSD": 2_400},
    {"Rank": 194, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 2_200},
    {"Rank": 195, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 2_000},
    {"Rank": 196, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 1_800},
    {"Rank": 197, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 1_600},
    {"Rank": 198, "Ticker": "ANT", "yTicker": "ANT-USD", "Name": "Aragon", "MarketCapUSD": 1_400},
    {"Rank": 199, "Ticker": "BLOCK", "yTicker": "BLOCK-USD", "Name": "Blocknet", "MarketCapUSD": 1_200},
    {"Rank": 200, "Ticker": "PRL", "yTicker": "PRL-USD", "Name": "Oyster Pearl", "MarketCapUSD": 1_000},
    {"Rank": 201, "Ticker": "XRPB", "yTicker": "XRPB-USD", "Name": "XRP Binar", "MarketCapUSD": 950},
    {"Rank": 202, "Ticker": "FET", "yTicker": "FET-USD", "Name": "Fetch.AI", "MarketCapUSD": 900},
    {"Rank": 203, "Ticker": "ELF", "yTicker": "ELF-USD", "Name": "aelf", "MarketCapUSD": 850},
    {"Rank": 204, "Ticker": "AGI", "yTicker": "AGI-USD", "Name": "SingularityNET", "MarketCapUSD": 800},
    {"Rank": 205, "Ticker": "KIN", "yTicker": "KIN-USD", "Name": "Kin", "MarketCapUSD": 750},
    {"Rank": 206, "Ticker": "REQ", "yTicker": "REQ-USD", "Name": "Request", "MarketCapUSD": 700},
    {"Rank": 207, "Ticker": "POWR", "yTicker": "POWR-USD", "Name": "Power Ledger", "MarketCapUSD": 650},
    {"Rank": 208, "Ticker": "VIBE", "yTicker": "VIBE-USD", "Name": "Viberate", "MarketCapUSD": 600},
    {"Rank": 209, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 550},
    {"Rank": 210, "Ticker": "MANA", "yTicker": "MANA-USD", "Name": "Decentraland", "MarketCapUSD": 500},
    {"Rank": 211, "Ticker": "NMR", "yTicker": "NMR-USD", "Name": "Numeraire", "MarketCapUSD": 480},
    {"Rank": 212, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 460},
    {"Rank": 213, "Ticker": "SNT", "yTicker": "SNT-USD", "Name": "Status", "MarketCapUSD": 440},
    {"Rank": 214, "Ticker": "CVC", "yTicker": "CVC-USD", "Name": "Civic", "MarketCapUSD": 420},
    {"Rank": 215, "Ticker": "POE", "yTicker": "POE-USD", "Name": "Po.et", "MarketCapUSD": 400},
    {"Rank": 216, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 380},
    {"Rank": 217, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 360},
    {"Rank": 218, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 340},
    {"Rank": 219, "Ticker": "C20", "yTicker": "C20-USD", "Name": "Crypto20", "MarketCapUSD": 320},
    {"Rank": 220, "Ticker": "WINGS", "yTicker": "WINGS-USD", "Name": "Wings DAO", "MarketCapUSD": 300},
    {"Rank": 221, "Ticker": "STORJ", "yTicker": "STORJ-USD", "Name": "Storj", "MarketCapUSD": 280},
    {"Rank": 222, "Ticker": "MDS", "yTicker": "MDS-USD", "Name": "MediShares", "MarketCapUSD": 260},
    {"Rank": 223, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 240},
    {"Rank": 224, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 220},
    {"Rank": 225, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 200},
    {"Rank": 226, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 180},
    {"Rank": 227, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 160},
    {"Rank": 228, "Ticker": "ANT", "yTicker": "ANT-USD", "Name": "Aragon", "MarketCapUSD": 140},
    {"Rank": 229, "Ticker": "BLOCK", "yTicker": "BLOCK-USD", "Name": "Blocknet", "MarketCapUSD": 120},
    {"Rank": 230, "Ticker": "PRL", "yTicker": "PRL-USD", "Name": "Oyster Pearl", "MarketCapUSD": 100},
    {"Rank": 231, "Ticker": "EDG", "yTicker": "EDG-USD", "Name": "Edgeless", "MarketCapUSD": 95},
    {"Rank": 232, "Ticker": "RFR", "yTicker": "RFR-USD", "Name": "Refereum", "MarketCapUSD": 90},
    {"Rank": 233, "Ticker": "TRST", "yTicker": "TRST-USD", "Name": "WeTrust", "MarketCapUSD": 85},
    {"Rank": 234, "Ticker": "WTC", "yTicker": "WTC-USD", "Name": "Waltonchain", "MarketCapUSD": 80},
    {"Rank": 235, "Ticker": "PAY", "yTicker": "PAY-USD", "Name": "TenX", "MarketCapUSD": 75},
    {"Rank": 236, "Ticker": "KMD", "yTicker": "KMD-USD", "Name": "Komodo", "MarketCapUSD": 70},
    {"Rank": 237, "Ticker": "PPT", "yTicker": "PPT-USD", "Name": "Populous", "MarketCapUSD": 65},
    {"Rank": 238, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 60},
    {"Rank": 239, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 55},
    {"Rank": 240, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 50},
    {"Rank": 241, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 48},
    {"Rank": 242, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 46},
    {"Rank": 243, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 44},
    {"Rank": 244, "Ticker": "CMT", "yTicker": "CMT-USD", "Name": "CyberMiles", "MarketCapUSD": 42},
    {"Rank": 245, "Ticker": "STMX", "yTicker": "STMX-USD", "Name": "StormX", "MarketCapUSD": 40},
    {"Rank": 246, "Ticker": "ADX", "yTicker": "ADX-USD", "Name": "AdEx", "MarketCapUSD": 38},
    {"Rank": 247, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 36},
    {"Rank": 248, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 34},
    {"Rank": 249, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 32},
    {"Rank": 250, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 30}
    {"Rank": 201, "Ticker": "XRPB", "yTicker": "XRPB-USD", "Name": "XRP Binar", "MarketCapUSD": 950},
    {"Rank": 202, "Ticker": "FET", "yTicker": "FET-USD", "Name": "Fetch.AI", "MarketCapUSD": 900},
    {"Rank": 203, "Ticker": "ELF", "yTicker": "ELF-USD", "Name": "aelf", "MarketCapUSD": 850},
    {"Rank": 204, "Ticker": "AGI", "yTicker": "AGI-USD", "Name": "SingularityNET", "MarketCapUSD": 800},
    {"Rank": 205, "Ticker": "KIN", "yTicker": "KIN-USD", "Name": "Kin", "MarketCapUSD": 750},
    {"Rank": 206, "Ticker": "REQ", "yTicker": "REQ-USD", "Name": "Request", "MarketCapUSD": 700},
    {"Rank": 207, "Ticker": "POWR", "yTicker": "POWR-USD", "Name": "Power Ledger", "MarketCapUSD": 650},
    {"Rank": 208, "Ticker": "VIBE", "yTicker": "VIBE-USD", "Name": "Viberate", "MarketCapUSD": 600},
    {"Rank": 209, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 550},
    {"Rank": 210, "Ticker": "MANA", "yTicker": "MANA-USD", "Name": "Decentraland", "MarketCapUSD": 500},
    {"Rank": 211, "Ticker": "NMR", "yTicker": "NMR-USD", "Name": "Numeraire", "MarketCapUSD": 480},
    {"Rank": 212, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 460},
    {"Rank": 213, "Ticker": "SNT", "yTicker": "SNT-USD", "Name": "Status", "MarketCapUSD": 440},
    {"Rank": 214, "Ticker": "CVC", "yTicker": "CVC-USD", "Name": "Civic", "MarketCapUSD": 420},
    {"Rank": 215, "Ticker": "POE", "yTicker": "POE-USD", "Name": "Po.et", "MarketCapUSD": 400},
    {"Rank": 216, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 380},
    {"Rank": 217, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 360},
    {"Rank": 218, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 340},
    {"Rank": 219, "Ticker": "C20", "yTicker": "C20-USD", "Name": "Crypto20", "MarketCapUSD": 320},
    {"Rank": 220, "Ticker": "WINGS", "yTicker": "WINGS-USD", "Name": "Wings DAO", "MarketCapUSD": 300},
    {"Rank": 221, "Ticker": "STORJ", "yTicker": "STORJ-USD", "Name": "Storj", "MarketCapUSD": 280},
    {"Rank": 222, "Ticker": "MDS", "yTicker": "MDS-USD", "Name": "MediShares", "MarketCapUSD": 260},
    {"Rank": 223, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 240},
    {"Rank": 224, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 220},
    {"Rank": 225, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 200},
    {"Rank": 226, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 180},
    {"Rank": 227, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 160},
    {"Rank": 228, "Ticker": "ANT", "yTicker": "ANT-USD", "Name": "Aragon", "MarketCapUSD": 140},
    {"Rank": 229, "Ticker": "BLOCK", "yTicker": "BLOCK-USD", "Name": "Blocknet", "MarketCapUSD": 120},
    {"Rank": 230, "Ticker": "PRL", "yTicker": "PRL-USD", "Name": "Oyster Pearl", "MarketCapUSD": 100},
    {"Rank": 231, "Ticker": "EDG", "yTicker": "EDG-USD", "Name": "Edgeless", "MarketCapUSD": 95},
    {"Rank": 232, "Ticker": "RFR", "yTicker": "RFR-USD", "Name": "Refereum", "MarketCapUSD": 90},
    {"Rank": 233, "Ticker": "TRST", "yTicker": "TRST-USD", "Name": "WeTrust", "MarketCapUSD": 85},
    {"Rank": 234, "Ticker": "WTC", "yTicker": "WTC-USD", "Name": "Waltonchain", "MarketCapUSD": 80},
    {"Rank": 235, "Ticker": "PAY", "yTicker": "PAY-USD", "Name": "TenX", "MarketCapUSD": 75},
    {"Rank": 236, "Ticker": "KMD", "yTicker": "KMD-USD", "Name": "Komodo", "MarketCapUSD": 70},
    {"Rank": 237, "Ticker": "PPT", "yTicker": "PPT-USD", "Name": "Populous", "MarketCapUSD": 65},
    {"Rank": 238, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 60},
    {"Rank": 239, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 55},
    {"Rank": 240, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 50},
    {"Rank": 241, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 48},
    {"Rank": 242, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 46},
    {"Rank": 243, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 44},
    {"Rank": 244, "Ticker": "CMT", "yTicker": "CMT-USD", "Name": "CyberMiles", "MarketCapUSD": 42},
    {"Rank": 245, "Ticker": "STMX", "yTicker": "STMX-USD", "Name": "StormX", "MarketCapUSD": 40},
    {"Rank": 246, "Ticker": "ADX", "yTicker": "ADX-USD", "Name": "AdEx", "MarketCapUSD": 38},
    {"Rank": 247, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 36},
    {"Rank": 248, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 34},
    {"Rank": 249, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 32},
    {"Rank": 250, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 30}
    {"Rank": 301, "Ticker": "RFR", "yTicker": "RFR-USD", "Name": "Refereum", "MarketCapUSD": 0.18},
    {"Rank": 302, "Ticker": "TRST", "yTicker": "TRST-USD", "Name": "WeTrust", "MarketCapUSD": 0.16},
    {"Rank": 303, "Ticker": "WTC", "yTicker": "WTC-USD", "Name": "Waltonchain", "MarketCapUSD": 0.15},
    {"Rank": 304, "Ticker": "PAY", "yTicker": "PAY-USD", "Name": "TenX", "MarketCapUSD": 0.14},
    {"Rank": 305, "Ticker": "KMD", "yTicker": "KMD-USD", "Name": "Komodo", "MarketCapUSD": 0.13},
    {"Rank": 306, "Ticker": "PPT", "yTicker": "PPT-USD", "Name": "Populous", "MarketCapUSD": 0.12},
    {"Rank": 307, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 0.11},
    {"Rank": 308, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 0.10},
    {"Rank": 309, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 0.095},
    {"Rank": 310, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 0.09},
    {"Rank": 311, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 0.085},
    {"Rank": 312, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 0.08},
    {"Rank": 313, "Ticker": "CMT", "yTicker": "CMT-USD", "Name": "CyberMiles", "MarketCapUSD": 0.075},
    {"Rank": 314, "Ticker": "STMX", "yTicker": "STMX-USD", "Name": "StormX", "MarketCapUSD": 0.07},
    {"Rank": 315, "Ticker": "ADX", "yTicker": "ADX-USD", "Name": "AdEx", "MarketCapUSD": 0.065},
    {"Rank": 316, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 0.06},
    {"Rank": 317, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 0.055},
    {"Rank": 318, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 0.05},
    {"Rank": 319, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 0.048},
    {"Rank": 320, "Ticker": "ANT", "yTicker": "ANT-USD", "Name": "Aragon", "MarketCapUSD": 0.046},
    {"Rank": 321, "Ticker": "BLOCK", "yTicker": "BLOCK-USD", "Name": "Blocknet", "MarketCapUSD": 0.044},
    {"Rank": 322, "Ticker": "PRL", "yTicker": "PRL-USD", "Name": "Oyster Pearl", "MarketCapUSD": 0.042},
    {"Rank": 323, "Ticker": "EDG", "yTicker": "EDG-USD", "Name": "Edgeless", "MarketCapUSD": 0.04},
    {"Rank": 324, "Ticker": "RFR", "yTicker": "RFR-USD", "Name": "Refereum", "MarketCapUSD": 0.038},
    {"Rank": 325, "Ticker": "TRST", "yTicker": "TRST-USD", "Name": "WeTrust", "MarketCapUSD": 0.036},
    {"Rank": 326, "Ticker": "WTC", "yTicker": "WTC-USD", "Name": "Waltonchain", "MarketCapUSD": 0.034},
    {"Rank": 327, "Ticker": "PAY", "yTicker": "PAY-USD", "Name": "TenX", "MarketCapUSD": 0.032},
    {"Rank": 328, "Ticker": "KMD", "yTicker": "KMD-USD", "Name": "Komodo", "MarketCapUSD": 0.03},
    {"Rank": 329, "Ticker": "PPT", "yTicker": "PPT-USD", "Name": "Populous", "MarketCapUSD": 0.028},
    {"Rank": 330, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 0.026},
    {"Rank": 331, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 0.024},
    {"Rank": 332, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 0.022},
    {"Rank": 333, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 0.02},
    {"Rank": 334, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 0.018},
    {"Rank": 335, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 0.016},
    {"Rank": 336, "Ticker": "CMT", "yTicker": "CMT-USD", "Name": "CyberMiles", "MarketCapUSD": 0.014},
    {"Rank": 337, "Ticker": "STMX", "yTicker": "STMX-USD", "Name": "StormX", "MarketCapUSD": 0.012},
    {"Rank": 338, "Ticker": "ADX", "yTicker": "ADX-USD", "Name": "AdEx", "MarketCapUSD": 0.01},
    {"Rank": 339, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 0.0095},
    {"Rank": 340, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 0.009},
    {"Rank": 341, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 0.0085},
    {"Rank": 342, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 0.008},
    {"Rank": 343, "Ticker": "ANT", "yTicker": "ANT-USD", "Name": "Aragon", "MarketCapUSD": 0.0075},
    {"Rank": 344, "Ticker": "BLOCK", "yTicker": "BLOCK-USD", "Name": "Blocknet", "MarketCapUSD": 0.007},
    {"Rank": 345, "Ticker": "PRL", "yTicker": "PRL-USD", "Name": "Oyster Pearl", "MarketCapUSD": 0.0065},
    {"Rank": 346, "Ticker": "EDG", "yTicker": "EDG-USD", "Name": "Edgeless", "MarketCapUSD": 0.006},
    {"Rank": 347, "Ticker": "RFR", "yTicker": "RFR-USD", "Name": "Refereum", "MarketCapUSD": 0.0055},
    {"Rank": 348, "Ticker": "TRST", "yTicker": "TRST-USD", "Name": "WeTrust", "MarketCapUSD": 0.005},
    {"Rank": 349, "Ticker": "WTC", "yTicker": "WTC-USD", "Name": "Waltonchain", "MarketCapUSD": 0.0045},
    {"Rank": 350, "Ticker": "PAY", "yTicker": "PAY-USD", "Name": "TenX", "MarketCapUSD": 0.004},
    {"Rank": 351, "Ticker": "KMD", "yTicker": "KMD-USD", "Name": "Komodo", "MarketCapUSD": 0.0038},
    {"Rank": 352, "Ticker": "PPT", "yTicker": "PPT-USD", "Name": "Populous", "MarketCapUSD": 0.0036},
    {"Rank": 353, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 0.0034},
    {"Rank": 354, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 0.0032},
    {"Rank": 355, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 0.003},
    {"Rank": 356, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 0.0028},
    {"Rank": 357, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 0.0026},
    {"Rank": 358, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 0.0024},
    {"Rank": 359, "Ticker": "CMT", "yTicker": "CMT-USD", "Name": "CyberMiles", "MarketCapUSD": 0.0022},
    {"Rank": 360, "Ticker": "STMX", "yTicker": "STMX-USD", "Name": "StormX", "MarketCapUSD": 0.002},
    {"Rank": 361, "Ticker": "ADX", "yTicker": "ADX-USD", "Name": "AdEx", "MarketCapUSD": 0.0019},
    {"Rank": 362, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 0.0018},
    {"Rank": 363, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 0.0017},
    {"Rank": 364, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 0.0016},
    {"Rank": 365, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 0.0015},
    {"Rank": 366, "Ticker": "ANT", "yTicker": "ANT-USD", "Name": "Aragon", "MarketCapUSD": 0.00145},
    {"Rank": 367, "Ticker": "BLOCK", "yTicker": "BLOCK-USD", "Name": "Blocknet", "MarketCapUSD": 0.0014},
    {"Rank": 368, "Ticker": "PRL", "yTicker": "PRL-USD", "Name": "Oyster Pearl", "MarketCapUSD": 0.00135},
    {"Rank": 369, "Ticker": "EDG", "yTicker": "EDG-USD", "Name": "Edgeless", "MarketCapUSD": 0.0013},
    {"Rank": 370, "Ticker": "RFR", "yTicker": "RFR-USD", "Name": "Refereum", "MarketCapUSD": 0.00125},
    {"Rank": 371, "Ticker": "TRST", "yTicker": "TRST-USD", "Name": "WeTrust", "MarketCapUSD": 0.0012},
    {"Rank": 372, "Ticker": "WTC", "yTicker": "WTC-USD", "Name": "Waltonchain", "MarketCapUSD": 0.00115},
    {"Rank": 373, "Ticker": "PAY", "yTicker": "PAY-USD", "Name": "TenX", "MarketCapUSD": 0.0011},
    {"Rank": 374, "Ticker": "KMD", "yTicker": "KMD-USD", "Name": "Komodo", "MarketCapUSD": 0.00105},
    {"Rank": 375, "Ticker": "PPT", "yTicker": "PPT-USD", "Name": "Populous", "MarketCapUSD": 0.001},
    {"Rank": 376, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 0.00095},
    {"Rank": 377, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 0.0009},
    {"Rank": 378, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 0.00085},
    {"Rank": 379, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 0.0008},
    {"Rank": 380, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 0.00075},
    {"Rank": 381, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 0.0007},
    {"Rank": 382, "Ticker": "CMT", "yTicker": "CMT-USD", "Name": "CyberMiles", "MarketCapUSD": 0.00065},
    {"Rank": 383, "Ticker": "STMX", "yTicker": "STMX-USD", "Name": "StormX", "MarketCapUSD": 0.0006},
    {"Rank": 384, "Ticker": "ADX", "yTicker": "ADX-USD", "Name": "AdEx", "MarketCapUSD": 0.00058},
    {"Rank": 385, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 0.00055},
    {"Rank": 386, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 0.00052},
    {"Rank": 387, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 0.0005},
    {"Rank": 388, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 0.00048},
    {"Rank": 389, "Ticker": "ANT", "yTicker": "ANT-USD", "Name": "Aragon", "MarketCapUSD": 0.00046},
    {"Rank": 390, "Ticker": "BLOCK", "yTicker": "BLOCK-USD", "Name": "Blocknet", "MarketCapUSD": 0.00044},
    {"Rank": 391, "Ticker": "PRL", "yTicker": "PRL-USD", "Name": "Oyster Pearl", "MarketCapUSD": 0.00042},
    {"Rank": 392, "Ticker": "EDG", "yTicker": "EDG-USD", "Name": "Edgeless", "MarketCapUSD": 0.00040},
    {"Rank": 393, "Ticker": "RFR", "yTicker": "RFR-USD", "Name": "Refereum", "MarketCapUSD": 0.00038},
    {"Rank": 394, "Ticker": "TRST", "yTicker": "TRST-USD", "Name": "WeTrust", "MarketCapUSD": 0.00036},
    {"Rank": 395, "Ticker": "WTC", "yTicker": "WTC-USD", "Name": "Waltonchain", "MarketCapUSD": 0.00034},
    {"Rank": 396, "Ticker": "PAY", "yTicker": "PAY-USD", "Name": "TenX", "MarketCapUSD": 0.00032},
    {"Rank": 397, "Ticker": "KMD", "yTicker": "KMD-USD", "Name": "Komodo", "MarketCapUSD": 0.0003},
    {"Rank": 398, "Ticker": "PPT", "yTicker": "PPT-USD", "Name": "Populous", "MarketCapUSD": 0.00028},
    {"Rank": 399, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 0.00026},
    {"Rank": 400, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 0.00024},
    {"Rank": 401, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 0.00022},
    {"Rank": 402, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 0.00020},
    {"Rank": 403, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 0.00019},
    {"Rank": 404, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 0.00018},
    {"Rank": 405, "Ticker": "CMT", "yTicker": "CMT-USD", "Name": "CyberMiles", "MarketCapUSD": 0.00017},
    {"Rank": 406, "Ticker": "STMX", "yTicker": "STMX-USD", "Name": "StormX", "MarketCapUSD": 0.00016},
    {"Rank": 407, "Ticker": "ADX", "yTicker": "ADX-USD", "Name": "AdEx", "MarketCapUSD": 0.00015},
    {"Rank": 408, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 0.000145},
    {"Rank": 409, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 0.00014},
    {"Rank": 410, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 0.000135},
    {"Rank": 411, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 0.00013},
    {"Rank": 412, "Ticker": "ANT", "yTicker": "ANT-USD", "Name": "Aragon", "MarketCapUSD": 0.000125},
    {"Rank": 413, "Ticker": "BLOCK", "yTicker": "BLOCK-USD", "Name": "Blocknet", "MarketCapUSD": 0.00012},
    {"Rank": 414, "Ticker": "PRL", "yTicker": "PRL-USD", "Name": "Oyster Pearl", "MarketCapUSD": 0.000115},
    {"Rank": 415, "Ticker": "EDG", "yTicker": "EDG-USD", "Name": "Edgeless", "MarketCapUSD": 0.00011},
    {"Rank": 416, "Ticker": "RFR", "yTicker": "RFR-USD", "Name": "Refereum", "MarketCapUSD": 0.000105},
    {"Rank": 417, "Ticker": "TRST", "yTicker": "TRST-USD", "Name": "WeTrust", "MarketCapUSD": 0.00010},
    {"Rank": 418, "Ticker": "WTC", "yTicker": "WTC-USD", "Name": "Waltonchain", "MarketCapUSD": 0.000095},
    {"Rank": 419, "Ticker": "PAY", "yTicker": "PAY-USD", "Name": "TenX", "MarketCapUSD": 0.00009},
    {"Rank": 420, "Ticker": "KMD", "yTicker": "KMD-USD", "Name": "Komodo", "MarketCapUSD": 0.000088},
    {"Rank": 421, "Ticker": "PPT", "yTicker": "PPT-USD", "Name": "Populous", "MarketCapUSD": 0.000086},
    {"Rank": 422, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 0.000084},
    {"Rank": 423, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 0.000082},
    {"Rank": 424, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 0.000080},
    {"Rank": 425, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 0.000078},
    {"Rank": 426, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 0.000076},
    {"Rank": 427, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 0.000074},
    {"Rank": 428, "Ticker": "CMT", "yTicker": "CMT-USD", "Name": "CyberMiles", "MarketCapUSD": 0.000072},
    {"Rank": 429, "Ticker": "STMX", "yTicker": "STMX-USD", "Name": "StormX", "MarketCapUSD": 0.000070},
    {"Rank": 430, "Ticker": "ADX", "yTicker": "ADX-USD", "Name": "AdEx", "MarketCapUSD": 0.000068},
    {"Rank": 431, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 0.000066},
    {"Rank": 432, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 0.000064},
    {"Rank": 433, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 0.000062},
    {"Rank": 434, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 0.000060},
    {"Rank": 435, "Ticker": "ANT", "yTicker": "ANT-USD", "Name": "Aragon", "MarketCapUSD": 0.000058},
    {"Rank": 436, "Ticker": "BLOCK", "yTicker": "BLOCK-USD", "Name": "Blocknet", "MarketCapUSD": 0.000056},
    {"Rank": 437, "Ticker": "PRL", "yTicker": "PRL-USD", "Name": "Oyster Pearl", "MarketCapUSD": 0.000054},
    {"Rank": 438, "Ticker": "EDG", "yTicker": "EDG-USD", "Name": "Edgeless", "MarketCapUSD": 0.000052},
    {"Rank": 439, "Ticker": "RFR", "yTicker": "RFR-USD", "Name": "Refereum", "MarketCapUSD": 0.000050},
    {"Rank": 440, "Ticker": "TRST", "yTicker": "TRST-USD", "Name": "WeTrust", "MarketCapUSD": 0.000048},
    {"Rank": 441, "Ticker": "WTC", "yTicker": "WTC-USD", "Name": "Waltonchain", "MarketCapUSD": 0.000046},
    {"Rank": 442, "Ticker": "PAY", "yTicker": "PAY-USD", "Name": "TenX", "MarketCapUSD": 0.000044},
    {"Rank": 443, "Ticker": "KMD", "yTicker": "KMD-USD", "Name": "Komodo", "MarketCapUSD": 0.000042},
    {"Rank": 444, "Ticker": "PPT", "yTicker": "PPT-USD", "Name": "Populous", "MarketCapUSD": 0.000040},
    {"Rank": 445, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 0.000038},
    {"Rank": 446, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 0.000036},
    {"Rank": 447, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 0.000034},
    {"Rank": 448, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 0.000032},
    {"Rank": 449, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 0.000030},
    {"Rank": 450, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 0.000028},
    {"Rank": 451, "Ticker": "CMT", "yTicker": "CMT-USD", "Name": "CyberMiles", "MarketCapUSD": 0.000026},
    {"Rank": 452, "Ticker": "STMX", "yTicker": "STMX-USD", "Name": "StormX", "MarketCapUSD": 0.000024},
    {"Rank": 453, "Ticker": "ADX", "yTicker": "ADX-USD", "Name": "AdEx", "MarketCapUSD": 0.000022},
    {"Rank": 454, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 0.000020},
    {"Rank": 455, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 0.000018},
    {"Rank": 456, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 0.000016},
    {"Rank": 457, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 0.000014},
    {"Rank": 458, "Ticker": "ANT", "yTicker": "ANT-USD", "Name": "Aragon", "MarketCapUSD": 0.000012},
    {"Rank": 459, "Ticker": "BLOCK", "yTicker": "BLOCK-USD", "Name": "Blocknet", "MarketCapUSD": 0.000010},
    {"Rank": 460, "Ticker": "PRL", "yTicker": "PRL-USD", "Name": "Oyster Pearl", "MarketCapUSD": 0.0000095},
    {"Rank": 461, "Ticker": "EDG", "yTicker": "EDG-USD", "Name": "Edgeless", "MarketCapUSD": 0.0000090},
    {"Rank": 462, "Ticker": "RFR", "yTicker": "RFR-USD", "Name": "Refereum", "MarketCapUSD": 0.0000085},
    {"Rank": 463, "Ticker": "TRST", "yTicker": "TRST-USD", "Name": "WeTrust", "MarketCapUSD": 0.0000080},
    {"Rank": 464, "Ticker": "WTC", "yTicker": "WTC-USD", "Name": "Waltonchain", "MarketCapUSD": 0.0000075},
    {"Rank": 465, "Ticker": "PAY", "yTicker": "PAY-USD", "Name": "TenX", "MarketCapUSD": 0.0000070},
    {"Rank": 466, "Ticker": "KMD", "yTicker": "KMD-USD", "Name": "Komodo", "MarketCapUSD": 0.0000065},
    {"Rank": 467, "Ticker": "PPT", "yTicker": "PPT-USD", "Name": "Populous", "MarketCapUSD": 0.0000060},
    {"Rank": 468, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 0.0000055},
    {"Rank": 469, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 0.0000050},
    {"Rank": 470, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 0.0000045},
    {"Rank": 471, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 0.0000040},
    {"Rank": 472, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 0.0000038},
    {"Rank": 473, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 0.0000036},
    {"Rank": 474, "Ticker": "CMT", "yTicker": "CMT-USD", "Name": "CyberMiles", "MarketCapUSD": 0.0000034},
    {"Rank": 475, "Ticker": "STMX", "yTicker": "STMX-USD", "Name": "StormX", "MarketCapUSD": 0.0000032},
    {"Rank": 476, "Ticker": "ADX", "yTicker": "ADX-USD", "Name": "AdEx", "MarketCapUSD": 0.0000030},
    {"Rank": 477, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 0.0000028},
    {"Rank": 478, "Ticker": "XVG", "yTicker": "XVG-USD", "Name": "Verge", "MarketCapUSD": 0.0000026},
    {"Rank": 479, "Ticker": "RLC", "yTicker": "RLC-USD", "Name": "iExec RLC", "MarketCapUSD": 0.0000024},
    {"Rank": 480, "Ticker": "GNO", "yTicker": "GNO-USD", "Name": "Gnosis", "MarketCapUSD": 0.0000022},
    {"Rank": 481, "Ticker": "ANT", "yTicker": "ANT-USD", "Name": "Aragon", "MarketCapUSD": 0.0000020},
    {"Rank": 482, "Ticker": "BLOCK", "yTicker": "BLOCK-USD", "Name": "Blocknet", "MarketCapUSD": 0.0000019},
    {"Rank": 483, "Ticker": "PRL", "yTicker": "PRL-USD", "Name": "Oyster Pearl", "MarketCapUSD": 0.0000018},
    {"Rank": 484, "Ticker": "EDG", "yTicker": "EDG-USD", "Name": "Edgeless", "MarketCapUSD": 0.0000017},
    {"Rank": 485, "Ticker": "RFR", "yTicker": "RFR-USD", "Name": "Refereum", "MarketCapUSD": 0.0000016},
    {"Rank": 486, "Ticker": "TRST", "yTicker": "TRST-USD", "Name": "WeTrust", "MarketCapUSD": 0.0000015},
    {"Rank": 487, "Ticker": "WTC", "yTicker": "WTC-USD", "Name": "Waltonchain", "MarketCapUSD": 0.0000014},
    {"Rank": 488, "Ticker": "PAY", "yTicker": "PAY-USD", "Name": "TenX", "MarketCapUSD": 0.0000013},
    {"Rank": 489, "Ticker": "KMD", "yTicker": "KMD-USD", "Name": "Komodo", "MarketCapUSD": 0.0000012},
    {"Rank": 490, "Ticker": "PPT", "yTicker": "PPT-USD", "Name": "Populous", "MarketCapUSD": 0.0000011},
    {"Rank": 491, "Ticker": "FUN", "yTicker": "FUN-USD", "Name": "FunFair", "MarketCapUSD": 0.0000010},
    {"Rank": 492, "Ticker": "NULS", "yTicker": "NULS-USD", "Name": "NULS", "MarketCapUSD": 0.00000095},
    {"Rank": 493, "Ticker": "IOST", "yTicker": "IOST-USD", "Name": "IOST", "MarketCapUSD": 0.00000090},
    {"Rank": 494, "Ticker": "AION", "yTicker": "AION-USD", "Name": "Aion", "MarketCapUSD": 0.00000085},
    {"Rank": 495, "Ticker": "DENT", "yTicker": "DENT-USD", "Name": "Dent", "MarketCapUSD": 0.00000080},
    {"Rank": 496, "Ticker": "MITH", "yTicker": "MITH-USD", "Name": "Mithril", "MarketCapUSD": 0.00000075},
    {"Rank": 497, "Ticker": "CMT", "yTicker": "CMT-USD", "Name": "CyberMiles", "MarketCapUSD": 0.00000070},
    {"Rank": 498, "Ticker": "STMX", "yTicker": "STMX-USD", "Name": "StormX", "MarketCapUSD": 0.00000065},
    {"Rank": 499, "Ticker": "ADX", "yTicker": "ADX-USD", "Name": "AdEx", "MarketCapUSD": 0.00000060},
    {"Rank": 500, "Ticker": "LRC", "yTicker": "LRC-USD", "Name": "Loopring", "MarketCapUSD": 0.00000055}
]
